# Note
#  - The JSON files generated by these scripts are already available in the winogender_data/ directory
#  - These scripts are fairly computationally expensive
#
# Perform attention intervention on Winobias filtered dev
#
python attention_intervention_winobias.py --gpt2-version distilgpt2 --do-filter True --split dev &&
python attention_intervention_winobias.py --gpt2-version gpt2 --do-filter True --split dev &&
python attention_intervention_winobias.py --gpt2-version gpt2-medium --do-filter True --split dev &&
python attention_intervention_winobias.py --gpt2-version gpt2-large --do-filter True --split dev &&
python attention_intervention_winobias.py --gpt2-version gpt2-xl --do-filter True --split dev &&
#
# Perform attention intervention on Winobias filtered test
#
python attention_intervention_winobias.py --gpt2-version distilgpt2 --do-filter True --split test &&
python attention_intervention_winobias.py --gpt2-version gpt2 --do-filter True --split test &&
python attention_intervention_winobias.py --gpt2-version gpt2-medium --do-filter True --split test &&
python attention_intervention_winobias.py --gpt2-version gpt2-large --do-filter True --split test &&
python attention_intervention_winobias.py --gpt2-version gpt2-xl --do-filter True --split test &&
#
# Perform attention intervention on Winogender unfiltered dev
#
python attention_intervention_winobias.py --gpt2-version distilgpt2 --do-filter False --split dev &&
python attention_intervention_winobias.py --gpt2-version gpt2 --do-filter False --split dev &&
python attention_intervention_winobias.py --gpt2-version gpt2-medium --do-filter False --split dev &&
python attention_intervention_winobias.py --gpt2-version gpt2-large --do-filter False --split dev &&
python attention_intervention_winobias.py --gpt2-version gpt2-xl --do-filter False --split dev &&
#
# Perform attention intervention on Winogender unfiltered test
#
python attention_intervention_winobias.py --gpt2-version distilgpt2 --do-filter False --split test &&
python attention_intervention_winobias.py --gpt2-version gpt2 --do-filter False --split test &&
python attention_intervention_winobias.py --gpt2-version gpt2-medium --do-filter False --split test &&
python attention_intervention_winobias.py --gpt2-version gpt2-large --do-filter False --split test &&
python attention_intervention_winobias.py --gpt2-version gpt2-xl --do-filter False --split test